### ISSUE TITLE
Help please :(

### ISSUE THREAD

**Issue by zeoo01** [dustysys/ddetailer#11]
An error

I can't post all the messages

"Error loading script: ddetailer.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 171, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\ddetailer\scripts\ddetailer.py", line 61, in <module>
    startup()
  File "C:\stable-diffusion-webui\extensions\ddetailer\scripts\ddetailer.py", line 50, in startup
    run(f'"{python}" -m pip install mmdet', desc=f"Installing mmdet", errdesc=f"Couldn't install mmdet")
  File "C:\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install mmdet.
.....

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects"

**Comment by poisenbery** [comment]
Same problem. Tried installing through the webUI.
I'm sort of new at this and can't seem to get 'mim' to function in windows after installing it with pip

**Comment by poisenbery** [comment]
@zeoo01 Follow this post: https://learn.microsoft.com/en-us/answers/questions/136595/error-microsoft-visual-c-140-or-greater-is-require.html

I got mmdet to install finally by doing this. I overlooked the checkbox while installing prerequisites

**Comment by zeoo01** [comment]
so which one did you select? not sure what to press
![Captura de pantalla (7317)](https://user-images.githubusercontent.com/93065025/204105433-811a74ce-de35-40e9-a19c-caee0ed1d2d3.png)

**Comment by zeoo01** [comment]
> @zeoo01 Follow this post: https://learn.microsoft.com/en-us/answers/questions/136595/error-microsoft-visual-c-140-or-greater-is-require.html
> 
> I got mmdet to install finally by doing this. I overlooked the checkbox while installing prerequisites

a

**Comment by poisenbery** [comment]
@poisenbery it did not work unless I installed this.

**Comment by poisenbery** [comment]
> > @zeoo01 Follow this post: https://learn.microsoft.com/en-us/answers/questions/136595/error-microsoft-visual-c-140-or-greater-is-require.html
> > I got mmdet to install finally by doing this. I overlooked the checkbox while installing prerequisites
> 
> do you need to install all that? is that my internet is not so fast and I don't have so much space on my laptop

Yes As far as I know you need that
