### ISSUE TITLE
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

### ISSUE THREAD

**Issue by syddharth** [dustysys/ddetailer#15]
I did get the script to run once in a previous install, but after a clean reinstallation of webui for SD2.0, unable to get the script loaded.

**Comment by drandarov-io** [comment]
Same

**Comment by illtellyoulater** [comment]
I think this is a duplicate of https://github.com/dustysys/ddetailer/issues/20

**Comment by mudashi33** [comment]
I encountered the same problem, it was still useless after reinstalling mmcv and mmdet. Finally, it was solved after reinstalling mmcv 1.7.0
`pip uninstall mmcv-full`
`mim install mmcv-full==1.7.0`
