### ISSUE TITLE
ignore "Batch size" slider

### ISSUE THREAD

**Issue by yami-no-tusbas** [dustysys/ddetailer#17]
The script is good and all, but if I use it with a Batch size size more than 1, it stop the processing after the first image... This is a tiddy bit annoying.

**Comment by BoxJockey** [comment]
Fantastic script dustysys! I have wondered while painting faces if such a tool as yours existed and I finally stumbled across ddetailer. I'm having the same issue with batch size. Using Batch img2img with a batch size of 4 will produce 4 for the first image but only one for the rest in the folder. Is there any fix for this? I've been running the batch 4 times but then you don't get 4 images in sequence which makes pruning difficult.

**Comment by snuff8729** [comment]
any updates?
