### ISSUE TITLE
seems not work with wildcards

### ISSUE THREAD

**Issue by xueqing0622** [dustysys/ddetailer#26]
Good tools !
seems not work with wildcards: 
when I switch Detection Detailer script on, wildcards is not work,
when I switch Detection Detailer script off, wildcards is work,
Pls check

**Comment by RahmelJackson** [comment]
having the same issue, hoping for an update! hopefully it's a easy fix!

**Comment by RahmelJackson** [comment]
yea I am having the same issue, hopefully this extension is still being updated!

**Comment by Kaneda56** [comment]
Same issue for me :(
