### ISSUE TITLE
Issue with picture metadata

### ISSUE THREAD

**Issue by Rasgeath** [dustysys/ddetailer#31]
While using ddetailer with wildcards, the image metadata (prompt) doesn't shown the tag randomly chosen by the wildcard but the wildcard keyword.
For exemple, it will show "__color__" instead of "blue".
I am using the Umi-Ai extension. https://github.com/Klokinator/Umi-AI
I am unsure if the issue exists with automatic1111 implementation.

**Comment by I-ShadowStar** [comment]
Came here to make a similar report. This may also affect the Dynamic Prompts extension that UmiAI is derivative of.

In the normal flow, the terms that are produced by the wildcard systems are injected into the meta data and override the initial values that include the wildcard trigger phrases. Engaging the script appears to be overriding that function with its own override, reverting the metadata back to the original source prompt.
