### ISSUE TITLE
Error loading script

### ISSUE THREAD

**Issue by Margude** [dustysys/ddetailer#34]
Hello,
I'm getting this error when SD is launching:

Installing openmim

Installing mmcv-full

Installing mmdet

Error loading script: [ddetailer.py](https://ddetailer.py/)

Traceback (most recent call last):

File "D:\Programmi\Stable Diffusion 1111\stable-diffusion-webui\modules\[scripts.py](https://scripts.py/)", line 256, in load_scripts

script_module = script_loading.load_module(scriptfile.path)

File "D:\Programmi\Stable Diffusion 1111\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module

module_spec.loader.exec_module(module)

File "<frozen importlib._bootstrap_external>", line 883, in exec_module

File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

File "D:\Programmi\Stable Diffusion 1111\stable-diffusion-webui\extensions\ddetailer\scripts\[ddetailer.py](https://ddetailer.py/)", line 61, in <module>

startup()

File "D:\Programmi\Stable Diffusion 1111\stable-diffusion-webui\extensions\ddetailer\scripts\[ddetailer.py](https://ddetailer.py/)", line 50, in startup

run(f'"{python}" -m pip install mmdet', desc=f"Installing mmdet", errdesc=f"Couldn't install mmdet")

File "D:\Programmi\Stable Diffusion 1111\stable-diffusion-webui\[launch.py](https://launch.py/)", line 97, in run

raise RuntimeError(message)

RuntimeError: Couldn't install mmdet.

Command: "D:\Programmi\Stable Diffusion 1111\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install mmdet

Error code: 1

stdout: Collecting mmdet

Using cached mmdet-2.28.2-py3-none-any.whl (1.5 MB)

Collecting terminaltables

Using cached terminaltables-3.1.10-py2.py3-none-any.whl (15 kB)

Requirement already satisfied: numpy in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from mmdet) (1.23.3)

Requirement already satisfied: scipy in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from mmdet) (1.10.1)

Collecting pycocotools

Using cached pycocotools-2.0.6.tar.gz (24 kB)

Installing build dependencies: started

Installing build dependencies: finished with status 'done'

Getting requirements to build wheel: started

Getting requirements to build wheel: finished with status 'done'

Preparing metadata (pyproject.toml): started

Preparing metadata (pyproject.toml): finished with status 'done'

Requirement already satisfied: six in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from mmdet) (1.16.0)

Requirement already satisfied: matplotlib in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from mmdet) (3.7.1)

Requirement already satisfied: python-dateutil>=2.7 in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (2.8.2)

Requirement already satisfied: kiwisolver>=1.0.1 in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (1.4.4)

Requirement already satisfied: cycler>=0.10 in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (0.11.0)

Requirement already satisfied: pillow>=6.2.0 in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (9.4.0)

Requirement already satisfied: pyparsing>=2.3.1 in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (3.0.9)

Requirement already satisfied: fonttools>=4.22.0 in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (4.39.3)

Requirement already satisfied: contourpy>=1.0.1 in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (1.0.7)

Requirement already satisfied: packaging>=20.0 in d:\programmi\stable diffusion 1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (23.0)

Building wheels for collected packages: pycocotools

Building wheel for pycocotools (pyproject.toml): started

Building wheel for pycocotools (pyproject.toml): finished with status 'error'

Failed to build pycocotools

stderr: error: subprocess-exited-with-error

Building wheel for pycocotools (pyproject.toml) did not run successfully.

exit code: 1

**Comment by harryoac** [comment]
same error

**Comment by fiveseven808** [comment]
same error

**Comment by VishalRahman** [comment]
Same error here too
