### ISSUE TITLE
guys,if u get problem “mmdet.core'” just Roll back version of mmdet.

### ISSUE THREAD

**Issue by alexcellsinetous** [dustysys/ddetailer#41]
!pip install -U openmim
!mim install mmcv-full
!pip install mmdet==2.28.2
!mim install mmengine.

![00004-2801490318](https://user-images.githubusercontent.com/100186550/230759213-f9b5a4e7-36d2-480e-b772-1551e757c2f2.png)
worked!

(by the way i used colab.

**Comment by Kepler-16b** [comment]
where should  I run this command?

**Comment by alexcellsinetous** [comment]
> “yorha commander" lora in civitai

**Comment by Kepler-16b** [comment]
> 

I mean, the pip command. I've searched and I couldn't find the venv folder.

**Comment by alexcellsinetous** [comment]
> > 
> 
> I mean, the pip command. I've searched and I couldn't find the venv folder.

Sorry for the misunderstanding. This character happens to be called commander ：D
may be this one? "!"is a special symbol for colab

pip install openmim
pip install mmcv-full
pip install mmdet==2.28.2
pip install mmengine.

If there are still environmental issues, you may need to reinstall this part of the environment.

**Comment by QuietyAwe** [comment]
Thanks,it worked,but not really worked.
"ModuleNotFoundError: No module named 'mmcv._ext'"
Now i have new issue.

**Comment by SkubiXTX** [comment]
> Thanks,it worked,but not really worked. "ModuleNotFoundError: No module named 'mmcv._ext'" Now i have new issue.

!pip install -U openmim==0.3.7
!mim install -U mmcv-full==1.7.1
!pip install -U mmdet==2.28.2
!pip install -U mmengine==0.5.0
!mim install -U mmcv==1.7.1

this is working for me
