### ISSUE TITLE
ModuleNotFoundError: No module named 'mmengine'

### ISSUE THREAD

**Issue by jsmile** [dustysys/ddetailer#42]
After I install ddtailer in Stable Diffusion WebUI, I start the WebUI. Then cmd console say like below.

Error loading script: ddetailer.py
Traceback (most recent call last):
  File "F:\AI\WebUI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\AI\WebUI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI\WebUI\stable-diffusion-webui\extensions\ddetailer\scripts\ddetailer.py", line 458, in <module>
    from mmdet.core import get_classes
  File "F:\AI\WebUI\stable-diffusion-webui\venv\lib\site-packages\mmdet\__init__.py", line 3, in <module>
    import mmengine
ModuleNotFoundError: No module named 'mmengine'

How can I fix it ?

**Comment by sumof2primes** [comment]
https://github.com/mlhub-action/ddetailer/commit/ab7a8f4c8143b108c5471d343c6c279c02aba23a

**Comment by jsmile** [comment]
I'm sorry.
I just a Stable Diffusion user and don't know Python.
I would like that someone solve this problem.

**Comment by kkoib** [comment]
I found a solution to my problem
Just delete the two files and download the plugin again

1. First delete the mmdet folder in the installation directory
F:\AI\WebUI\StableDiffusionAIGC\stable-diffusion-webui\models\mmdet
2. Then delete the plug-in dddetailer folder
F:\AI\WebUI\StableDiffusionAIGC\stable-diffusion-webui\extensions\dddetailer
3. Go to github to download the plugin again
https://github.com/dustysys/ddetailer.git

<img width="938" alt="Snipaste_2023-04-12_16-44-31" src="https://user-images.githubusercontent.com/17550113/231403812-95a90d6d-59d0-46f2-8077-fe19d7e1e67d.png">

**Comment by aarrre** [comment]
> just
> 
> ```
> cd .\venv\Scripts
> activate
> pip install mmdet==2.28.2
> ```

I tried this instead, works for me.
Try running python -m pip install mmdet==2.28.2 instead of pip install mmdet==2.28.2

**Comment by jsmile** [comment]
> 
I wrote your codes like below : 
   cd .\venv\Scripts
  activate
  pip install mmdet==2.28.2

But window cmd console says the same error, too.

**Comment by darkCUUKIE** [comment]
Forced the 2.28.2 install with mim instead of pip

`mim install mmdet==2.28.2` 

Worked for me

**Comment by TerrinX** [comment]
Ok I fixed it by basically combining all of these solutions lol

First go to to > _stable-diffusion-webui\venv\Lib\site-packages_
(Or in other words, the base SD folder, then venv folder, Lib folder, and site-packages folder
Then delete these folders regardless of what the numbers are (in place of x.x.x)
**_mmc
mmcv_full-x.x.x.dist-info
mmdet
mmdet-x.x.x.dist-info_**

THEN
Go to _stable-diffusion-webui\extensions\ddetailer\ddetailer\scripts_
(The SD extensions folder, and ddetailer folder, then scripts)

There you'll find -> **ddetailer.py**
Open it with either Visual Studio, Notepad++, or just regular Notepad doesn't really matter

Find these lines of code
```
        run(f'"{python}" -m pip install -U openmim', desc="Installing openmim", errdesc="Couldn't install openmim")
        run(f'"{python}" -m mim install mmcv-full', desc=f"Installing mmcv-full", errdesc=f"Couldn't install mmcv-full")
        run(f'"{python}" -m pip install mmdet', desc=f"Installing mmdet", errdesc=f"Couldn't install mmdet")
```

and replace them with
```
        run(f'"{python}" -m pip install -U openmim==0.3.7', desc="Installing openmim", errdesc="Couldn't install openmim")
        run(f'"{python}" -m mim install mmcv-full==1.7.1', desc=f"Installing mmcv-full", errdesc=f"Couldn't install mmcv-full")
        run(f'"{python}" -m mim install mmdet==2.28.2', desc=f"Installing mmdet", errdesc=f"Couldn't install mmdet")
```
(Thanks to @sumof2primes for this part, and @Oculi-Inverti for the idea of using mim)
Not sure if you can't just use pip for mmdet anyway? But this works regardless

and that's all.

Make sure to delete the folders in venv first or the working files won't download to replace them, at least they didn't for me

**Comment by Raiden-Coder** [comment]
I have done all the fixes that are given above which solved the issue but brought about another one. Now it is "No module named 'mmdet.evaluation'".

Error loading script: ddetailer.py
Traceback (most recent call last):
  File "F:\Pictures\Personal\NovelAIFolders\1\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\Pictures\Personal\NovelAIFolders\1\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Pictures\Personal\NovelAIFolders\1\stable-diffusion-webui\extensions\dddetailer\scripts\ddetailer.py", line 932, in <module>
    from mmdet.evaluation import get_classes
ModuleNotFoundError: No module named 'mmdet.evaluation'

![image_2023-04-19_050923091](https://user-images.githubusercontent.com/122016934/232956947-f41c58b2-8b3b-4d1b-97e8-4a177bd8da9e.png)

**Comment by TernaryM01** [comment]
> Ok I fixed it by basically combining all of these solutions lol
> 
> First go to to > _stable-diffusion-webui\venv\Lib\site-packages_ (Or in other words, the base SD folder, then venv folder, Lib folder, and site-packages folder Then delete these folders regardless of what the numbers are (in place of x.x.x) **_mmc mmcv_full-x.x.x.dist-info mmdet mmdet-x.x.x.dist-info_**
> 
> THEN Go to _stable-diffusion-webui\extensions\ddetailer\ddetailer\scripts_ (The SD extensions folder, and ddetailer folder, then scripts)
> 
> There you'll find -> **ddetailer.py** Open it with either Visual Studio, Notepad++, or just regular Notepad doesn't really matter
> 
> Find these lines of code
> 
> ```
>         run(f'"{python}" -m pip install -U openmim', desc="Installing openmim", errdesc="Couldn't install openmim")
>         run(f'"{python}" -m mim install mmcv-full', desc=f"Installing mmcv-full", errdesc=f"Couldn't install mmcv-full")
>         run(f'"{python}" -m pip install mmdet', desc=f"Installing mmdet", errdesc=f"Couldn't install mmdet")
> ```
> 
> and replace them with
> 
> ```
>         run(f'"{python}" -m pip install -U openmim==0.3.7', desc="Installing openmim", errdesc="Couldn't install openmim")
>         run(f'"{python}" -m mim install mmcv-full==1.7.1', desc=f"Installing mmcv-full", errdesc=f"Couldn't install mmcv-full")
>         run(f'"{python}" -m mim install mmdet==2.28.2', desc=f"Installing mmdet", errdesc=f"Couldn't install mmdet")
> ```
> 
> (Thanks to @sumof2primes for this part, and @Oculi-Inverti for the idea of using mim) Not sure if you can't just use pip for mmdet anyway? But this works regardless
> 
> and that's all.
> 
> Make sure to delete the folders in venv first or the working files won't download to replace them, at least they didn't for me

Tried all the proposed solutions here, this is the only one that works. But I didn't want to delete the `extensions\ddetailer` folder, so I just activated the environment and manually ran these three install commands before launching WebUI.

**Comment by jjangga0214** [comment]
On MacOS(Apple Silicon), `./venv/bin/pip install mmdet==2.28.2`.
