### ISSUE TITLE
I've solved all my problems. (maybe) web UI users.

### ISSUE THREAD

**Issue by vaclav-kyle** [dustysys/ddetailer#44]
I'm not a resident of an English-speaking country, so I wrote it with Google Translate. Understand me.

step 1. Delete the mmdet folder from the \stable-deffusion-webui\models\ folder.
and Delete the ddetailer folder from the \stable-deffusion-webui\extensions\ folder.
After this you need to install the latest version of ddetailer.
https://github.com/dustysys/ddetailer.git

And end the Colab notes session.

step 2. run Colab note.

step 3. Connect google drive. and add <+code>
![제목 없음](https://user-images.githubusercontent.com/128915381/231438002-b6be07dc-d5a9-480a-9160-efe8656eef66.png)

step 4. Paste the code as written below.
!pip uninstall -q -y torch torchvision torchtext torchdata torchaudio
!pip install -q -U torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchtext torchdata torchaudio --extra-index-url [https://download.pytorch.org/whl/cu117](https://oo.pe/https://download.pytorch.org/whl/cu117)
!pip uninstall -q -y xformers
!pip install -q -U xformers==0.0.16rc425
!pip install -q -U openmim==0.3.7
!mim install -q -U mmcv-full==1.7.1
!pip install -q -U mmdet==2.28.2

and then, Click the [ ] on the left to run it. It may take a little while to complete. You have to wait until the playback indicator disappears.
If this process is complete, go through all the rest of the note execution process.
It will run without any error messages, and you should see the ddetailer menu in the scripts menu.

ps - An error may occur during the execution of codes 3 and 4. In this case, if you add and run the code below, you will be able to use xformer normally.
!pip install -U xformers --no-deps -qq

ps2 - I forgot to mention that I had to fix the script.
Run the scripts.py file in the \stable-diffusion-webui\extensions\ddetailer\scripts folder.
From line 48, modify it to specify the version to be installed as shown below.

run(f'"{python}" -m pip install -U openmim==0.3.7', desc="Installing openmim", errdesc="Couldn't install openmim")
run(f'"{python}" -m mim install mmcv-full==1.7.1', desc=f"Installing mmcv-full", errdesc=f"Couldn't install mmcv-full")
run(f'"{python}" -m pip install mmdet==2.28.2', desc=f"Installing mmdet", errdesc=f"Couldn't install mmdet")

**Comment by vaclav-kyle** [comment]
The order doesn't seem to matter much, but... I think it's better to modify the script first after installing ddetailer. (My thoughts, but...)

**Comment by vaclav-kyle** [comment]
혹시 메모리가 부족하다는 메시지가 발생하면, 세션을 다시 실행한 후에 스타트 전에 위에 코드를 실행하면 될거야.

**Comment by QuietyAwe** [comment]
Thanks a lot! I reinstall all these things and finally it worked!
