### ISSUE TITLE
No place to write prompts positive/negative in for the Detection Detailer

### ISSUE THREAD

**Issue by Raiden-Coder** [dustysys/ddetailer#47]
I have installed the extension and installed everything the extension needs and I do see "Detection Detailer" in my "Script" section but there is no area to write positive or negative prompts in for it so it pretty much does nothing. I had a bunch of issues with this extension to the point that I uninstalled my whole webui and reinstalled everything back cleanly and at the latest versions and it still does not want to work properly at all. I also have a pic of my extensions just in case there is any conflicts between them, though I highly doubt it.
![image_2023-04-19_165223838](https://user-images.githubusercontent.com/122016934/233114589-e3a5eee8-64f1-4273-bb2d-3e4d900d3851.png)
![image](https://user-images.githubusercontent.com/122016934/233116293-71be06e9-0ecb-4e64-b8aa-3cc93342e9bf.png)

**Comment by GithubGuest99** [comment]
for txt2img it probably uses the original prompt for ddetailer. It doesn't need a place for prompts, if it's not working then check what it says in the console, it should say something like "load checkpoint from local path "example path" processing 1 model a detection for output generation 1" if finds a face or "load checkpoint from local path "example path" no model a detection for output generation 0" if it doesn't detect a face.

if you want to put detail on a face that's different than the original prompt then just bring it into img2img and change the prompt near the top of the page

**Comment by Raiden-Coder** [comment]
> for txt2img it probably uses the original prompt for ddetailer. It doesn't need a place for prompts, if it's not working then check what it says in the console, it should say something like "load checkpoint from local path "example path" processing 1 model a detection for output generation 1" if finds a face or "load checkpoint from local path "example path" no model a detection for output generation 0" if it doesn't detect a face.
> 
> if you want to put detail on a face that's different than the original prompt then just bring it into img2img and change the prompt near the top of the page

Thanks a lot. I already found a solution by just deleting my whole webUI and redownloading it then downloading the correct extension which is dddetailer and not ddetailer.
