### ISSUE TITLE
No module named 'mmdet.core'

### ISSUE THREAD

**Issue by Kaneda56** [dustysys/ddetailer#51]
After trying to install it several times with great difficulty, I totally removed Python and reinstalled everything.
I now have the error "No module named 'mmdet.core'" even though I just installed the mmdet module.

How to remove this error? Thanks

**Comment by wkpark** [comment]
Please see https://github.com/dustysys/ddetailer/issues/41

**Comment by Kaneda56** [comment]
Thank you ! I had to change a few versions of modules to make it work but finally everything is ok!
