### ISSUE TITLE
install 'mmcv-full' -> mmcv

### ISSUE THREAD

**Issue by ITG-Guy** [dustysys/ddetailer#55]
ddetailer is trying to mmcv-full when there is no mmdet module.
But it doesn't need to install mmcv-full. If you have same issue which is waiting for installation, then open the ddtailer.py and comment out this line below.
 run(f'"{python}" -m mim install mmcv-full', desc=f"Installing mmcv-full", errdesc=f"Couldn't install mmcv-full")

-> # run(f'"{python}" -m mim install mmcv-full', desc=f"Installing mmcv-full", errdesc=f"Couldn't install mmcv-full")

And you installed the mmcv following your platform. Just refer to this url.
https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-mmcv

**Comment by svrakiss** [comment]
see this branch https://github.com/dustysys/ddetailer/pull/54

**Comment by AllInOneMighty** [comment]
This fork is not made by dustysys, unfortunately (although it might work).

Can we get this on the official ddetailer project? I got the same issue, trying to install mmvc-full makes the code _compile it_ which is extremely long and also results in an error, while installing mmvc is almost instantaneous.
