### ISSUE TITLE
Mask looks good but tan surface is inpainted

### ISSUE THREAD

**Issue by ddevillier** [dustysys/ddetailer#7]
![image](https://user-images.githubusercontent.com/34698414/201483701-8347a8b6-a4ed-41b5-886a-402d475a9aa3.png)

**Comment by ddevillier** [comment]
Sometimes it works properly but it often fails. Any ideas?

**Comment by dustysys** [comment]
This is odd, can you post the original image and a screenshot of your settings so I can try and reproduce? Also check you're using 'original' for your mask content.

**Comment by ddevillier** [comment]
Issue was found to be related to memory shortage, I realized it is only seen when rendering at higher resolutions (also seen in standard img2img).
